name: Bazel Build

on: [pull_request]

env:
   DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

jobs:
  macos:
    name: Bazel
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build & Test
      run: bazelisk test --build_tests_only //Tests:all
